language: generic

dist: xenial

before_script:
    - shellcheck --version

script:
    - source ${TRAVIS_BUILD_DIR}/build.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#polybar"
    template:
      - " %{repository_name}/%{branch} | \"%{commit_subject}\" by %{author} | Commit #%{commit} + Build #%{build_number} = %{result}"
    use_notice: true
    on_success: always
    on_failure: never
